"""Add date field to Task model

Revision ID: 428e8e15a259
Revises: f94ddcb1bb72
Create Date: 2025-03-14 12:02:50.279776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428e8e15a259'
down_revision = 'f94ddcb1bb72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
